// Define coarse-grained permissions. These can be extended later.
export const PERMISSIONS = {
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  MANAGE_CASHFLOW: 'MANAGE_CASHFLOW',
  VIEW_PATIENTS: 'VIEW_PATIENTS',
  MANAGE_APPOINTMENTS: 'MANAGE_APPOINTMENTS',
};

// Role -> default permissions map. Keep this separate from runtime checks
export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [PERMISSIONS.MANAGE_USERS, PERMISSIONS.MANAGE_CASHFLOW, PERMISSIONS.VIEW_PATIENTS, PERMISSIONS.MANAGE_APPOINTMENTS],
  KINESIOLOGO: [PERMISSIONS.VIEW_PATIENTS, PERMISSIONS.MANAGE_APPOINTMENTS],
  SECRETARIA: [PERMISSIONS.VIEW_PATIENTS, PERMISSIONS.MANAGE_APPOINTMENTS, PERMISSIONS.MANAGE_CASHFLOW],
};

export default PERMISSIONS;
