CREATE TABLE "WhatsAppCoverage" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "category" TEXT NOT NULL DEFAULT 'obra_social',
  "aliases" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "WhatsAppCoverage_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "WhatsAppCoverage_name_key" ON "WhatsAppCoverage"("name");
CREATE INDEX "WhatsAppCoverage_isActive_sortOrder_idx" ON "WhatsAppCoverage"("isActive", "sortOrder");

INSERT INTO "WhatsAppCoverage" ("id", "name", "category", "aliases", "isActive", "sortOrder", "createdAt", "updatedAt") VALUES
('wacov_001', 'ACTIVA SALUD', 'obra_social', ARRAY['OSFATLYF', 'OSCONARA'], true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_002', 'AMEBPBA', 'obra_social', ARRAY['Banco Provincia'], true, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_003', 'AMFFA', 'obra_social', ARRAY['Farmacéuticos'], true, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_004', 'AMSTERDAM SALUD', 'prepaga', ARRAY['Amsterdam'], true, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_005', 'APRES S.A.', 'prepaga', ARRAY['APRES', 'APRES SA'], true, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_006', 'APSOT', 'obra_social', ARRAY[]::TEXT[], true, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_007', 'ASI', 'obra_social', ARRAY['Asistencia Sanitaria Integral'], true, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_008', 'ASOCIACIÓN ECLESIÁSTICA SAN PEDRO', 'obra_social', ARRAY['San Pedro'], true, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_009', 'AVALIAN', 'prepaga', ARRAY['AC Salud'], true, 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_010', 'CASA', 'obra_social', ARRAY[]::TEXT[], true, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_011', 'CENTRO MÉDICO PUEYRREDÓN', 'obra_social', ARRAY['Pueyrredón'], true, 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_012', 'COLEGIO DE ESCRIBANOS', 'obra_social', ARRAY[]::TEXT[], true, 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_013', 'COMEI', 'obra_social', ARRAY['Odontólogos'], true, 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_014', 'DASMI', 'obra_social', ARRAY[]::TEXT[], true, 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_015', 'DASUTEN', 'obra_social', ARRAY[]::TEXT[], true, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_016', 'E.W. HOPE', 'obra_social', ARRAY['William Hope'], true, 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_017', 'FEDERADA SALUD', 'prepaga', ARRAY['Federada'], true, 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_018', 'FUTBOLISTAS', 'obra_social', ARRAY[]::TEXT[], true, 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_019', 'GLOBAL EMPRESARIA', 'obra_social', ARRAY[]::TEXT[], true, 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_020', 'IOMA', 'obra_social', ARRAY[]::TEXT[], true, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_021', 'JERÁRQUICOS SALUD', 'prepaga', ARRAY['Jerárquicos'], true, 21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_022', 'LUIS PASTEUR', 'obra_social', ARRAY['Pasteur'], true, 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_023', 'MEDICUS', 'prepaga', ARRAY[]::TEXT[], true, 23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_024', 'MEDIFÉ', 'prepaga', ARRAY['Medifé Salud', 'Medife'], true, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_025', 'OPDEA', 'obra_social', ARRAY[]::TEXT[], true, 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_026', 'OSDOP', 'obra_social', ARRAY['Docentes particulares'], true, 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_027', 'OSFATUN', 'obra_social', ARRAY[]::TEXT[], true, 27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_028', 'OSPE', 'obra_social', ARRAY['Petroleros'], true, 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_029', 'OSPEDYC', 'obra_social', ARRAY[]::TEXT[], true, 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_030', 'OSPEPBA', 'obra_social', ARRAY['Escribanías'], true, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_031', 'OSPIA', 'obra_social', ARRAY['Alimentación'], true, 31, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_032', 'OSPSA', 'obra_social', ARRAY['Sanidad'], true, 32, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_033', 'OSPTV', 'obra_social', ARRAY['Televisión'], true, 33, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_034', 'OSSEG', 'obra_social', ARRAY['Integral', 'Adherente'], true, 34, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_035', 'PODER JUDICIAL', 'obra_social', ARRAY[]::TEXT[], true, 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_036', 'PREVENCIÓN SALUD', 'prepaga', ARRAY['Prevención'], true, 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_037', 'SANCOR SALUD', 'prepaga', ARRAY['Sancor'], true, 37, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_038', 'SCIS S.A.', 'prepaga', ARRAY['SCIS', 'SCIS SA'], true, 38, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_039', 'SWISS MEDICAL', 'prepaga', ARRAY['Swiss'], true, 39, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_040', 'UNION PERSONAL', 'obra_social', ARRAY['UP'], true, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_041', 'LA HOLANDO ART', 'art', ARRAY['Holando Art', 'Holando'], true, 41, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_042', 'LA SEGUNDA ART', 'art', ARRAY['La Segunda', 'Segunda Art'], true, 42, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_043', 'OMINT ART (SERENA)', 'art', ARRAY['OMINT ART', 'Serena'], true, 43, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_044', 'PARANÁ ART', 'art', ARRAY['Paraná Art', 'Paraná'], true, 44, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_045', 'RECONQUISTA ART', 'art', ARRAY['Reconquista Art', 'Reconquista'], true, 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_046', 'RURAL MUTUAL ART', 'art', ARRAY['Rural Mutual Art', 'Rural Mutual'], true, 46, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_047', 'SAN FRANCISCO ART', 'art', ARRAY[]::TEXT[], true, 47, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('wacov_048', 'SMG ART (Swiss Medical)', 'art', ARRAY['SMG ART', 'SMG'], true, 48, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
